name: CMake

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout github
      uses: actions/checkout@develop
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
    - name: Install dependencies, compile, check formatting, test and create docs
      uses: docker://quay.io/cbgeo/mpm
        with:
          entrypoint: /bin/sh
          args: |
            mkdir -p build
	    [ "$(ls -A build)" ] && rm -rf build/*
            cd build
            source /etc/profile.d/modules.sh
            export MODULEPATH=$MODULEPATH:/usr/share/modulefiles
            module load mpi/openmpi-x86_64
            export CXX_COMPILER=mpicxx
            cmake -GNinja -DMPM_BUILD_LIB=Off -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DKAHIP_ROOT=/home/cbgeo/KaHIP/ -DPARTIO_ROOT=/home/cbgeo/partio/ ..
            ninja -j2
            ctest -VV
            mpirun -n 4 ./mpmtest [mpi]
